'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FRMCadastroUsuario
    
    '''<summary>
    '''BTN_Limpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Limpar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''BTN_Gravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Gravar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''BTN_Excluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Excluir As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''CAMPO_MENSAGEM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAMPO_MENSAGEM As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LBL_Mensagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_Mensagem As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TXT_C001_Cpf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_C001_Cpf As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TXT_C001_Nome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_C001_Nome As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TXT_C001_SobreNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_C001_SobreNome As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TXT_C001_Detalhe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_C001_Detalhe As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TXT_C001_Email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_C001_Email As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DDL_C001_Sexo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_C001_Sexo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CAMPO_ACESSO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAMPO_ACESSO As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TXT_C001_Senha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_C001_Senha As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TXT_C001_Senha_Repetir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_C001_Senha_Repetir As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DDL_C001_TrocarSenha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_C001_TrocarSenha As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TXT_C001_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_C001_Date As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TXT_C001_Tentativa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_C001_Tentativa As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DDL_C001_Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_C001_Status As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CAMPO_MEMBRESIA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAMPO_MEMBRESIA As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DDL_C003_Igreja control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_C003_Igreja As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DDL_C005_Perfil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_C005_Perfil As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TXT_Matricula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Matricula As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LBL_C001_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_C001_ID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LBL_Membresia_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_Membresia_ID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GridPesquisa_01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridPesquisa_01 As Global.System.Web.UI.WebControls.Repeater
End Class
