'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FRMFrequencia
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ASP_MENU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ASP_MENU_RESIDENCIA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_RESIDENCIA As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ASP_MENU_ITEM_CLASSE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_ITEM_CLASSE As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ASP_MENU_ITEM_ALUNOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_ITEM_ALUNOS As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ASP_MENU_FREQUENCIA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_FREQUENCIA As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ASP_MENU_ITEM_PLANO_AULA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_ITEM_PLANO_AULA As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ASP_MENU_RELATORIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_RELATORIO As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LBL_C001_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_C001_ID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LBL_FrequenciaUnique control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_FrequenciaUnique As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GridPesquisa_01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridPesquisa_01 As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''BTN_Limpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Limpar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''BTN_Gravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Gravar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''CAMPO_MENSAGEM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAMPO_MENSAGEM As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LBL_Mensagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_Mensagem As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DDL_PLANO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_PLANO As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TXT_DATA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_DATA As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LBL_ALTERACAO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_ALTERACAO As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''CheckBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CheckBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''GridPesquisa_LST_ALUNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridPesquisa_LST_ALUNO As Global.System.Web.UI.WebControls.Repeater
End Class
