'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FRMPlanoAula
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ASP_MENU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ASP_MENU_RESIDENCIA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_RESIDENCIA As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ASP_MENU_ITEM_CLASSE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_ITEM_CLASSE As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ASP_MENU_ITEM_ALUNOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_ITEM_ALUNOS As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ASP_MENU_FREQUENCIA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_FREQUENCIA As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ASP_MENU_ITEM_PLANO_AULA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_ITEM_PLANO_AULA As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ASP_MENU_RELATORIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_RELATORIO As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''BTN_Limpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Limpar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''BTN_Gravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Gravar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''BTN_Excluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Excluir As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''CAMPO_MENSAGEM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAMPO_MENSAGEM As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LBL_Mensagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_Mensagem As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TXT_Descricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Descricao As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TXT_Professor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Professor As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TXT_DATA_PREVISTO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_DATA_PREVISTO As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TXT_Hora_Aula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Hora_Aula As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LBL_CH_RESTANTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_CH_RESTANTE As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TXT_Observacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Observacao As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LBL_C001_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_C001_ID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LBL_Membresia_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_Membresia_ID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GridPesquisa_01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridPesquisa_01 As Global.System.Web.UI.WebControls.Repeater
End Class
