'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ListaAlunoCNC
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''ASP_MENU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ASP_MENU_RESIDENCIA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_RESIDENCIA As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ASP_MENU_ITEM_CLASSE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_ITEM_CLASSE As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ASP_MENU_ITEM_ALUNOS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_ITEM_ALUNOS As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ASP_MENU_FREQUENCIA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_FREQUENCIA As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ASP_MENU_ITEM_PLANO_AULA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_ITEM_PLANO_AULA As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ASP_MENU_RELATORIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASP_MENU_RELATORIO As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''BTN_Limpar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Limpar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''BTN_Gravar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Gravar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''BTN_Excluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_Excluir As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''CAMPO_MENSAGEM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAMPO_MENSAGEM As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LBL_Mensagem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_Mensagem As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TXT_NOME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_NOME As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TXT_CPF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_CPF As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TXT_DATA_NASC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_DATA_NASC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DDL_Escolaridade control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_Escolaridade As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''TXT_Celular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Celular As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TXT_Equipe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Equipe As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TXT_Celula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Celula As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TXT_Dicipulador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Dicipulador As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TXT_Batismo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_Batismo As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DDL_SITUACAO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_SITUACAO As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''LBL_C001_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_C001_ID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LBL_Membresia_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_Membresia_ID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GridPesquisa_01 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridPesquisa_01 As Global.System.Web.UI.WebControls.Repeater
End Class
